### ISSUE TITLE
issues pip installing locally

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CILViewer#263]
When I want to run the web app, this is my procedure:

- create an environement using:
- pip install the viewer from master / whatever branch I want to test

Whenever I pip install I get the error:

```python
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    ERROR: Command errored out with exit status 1:
     command: 'D:\lhe97136\Miniconda3\envs\cilviewer_webapp_trame2\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lhe97136\\AppData\\Local\\Temp\\pip-req-build-psbkn0pj\\setup.py'"'"'; __file__='"'"'C:\\Users\\lhe97136\\AppData\\Local\\Temp\\pip-req-build-psbkn0pj\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\lhe97136\AppData\Local\Temp\pip-pip-egg-info-tz7itw1a'
         cwd: C:\Users\lhe97136\AppData\Local\Temp\pip-req-build-psbkn0pj\
    Complete output (10 lines):
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lhe97136\AppData\Local\Temp\pip-req-build-psbkn0pj\setup.py", line 39, in <module>
        git_version_string = subprocess.check_output('git describe', shell=True).decode("utf-8").rstrip()[1:]
      File "D:\lhe97136\Miniconda3\envs\cilviewer_webapp_trame2\lib\subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "D:\lhe97136\Miniconda3\envs\cilviewer_webapp_trame2\lib\subprocess.py", line 524, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command 'git describe' returned non-zero exit status 128.
```

my hack is to manually set a version number in the setup.py, but what should we be doing to prevent this? Do I have to conda build and install instead or something?

**Comment by lauramurgatroyd** [comment]
Instead of the hack, works fine if I use ` pip install . --use-feature=in-tree-build `
