### ISSUE TITLE
With vtk8 Tiff reading tests fail whereas with vtk9 they do not

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CILViewer#296]
In an environment with current master and vtk8.1.2 I get the following errors:

> ======================================================================
> FAIL: test_tiff_cropped_reader (test_cropped_readers.TestCroppedReaders)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\Users\lhe97136\Work\CCPi\CILViewer\Wrappers\Python\test\test_cropped_readers.py", line 107, in test_tiff_cropped_reader
>     self.check_values(target_z_extent, reader.GetOutput())
>   File "C:\Users\lhe97136\Work\CCPi\CILViewer\Wrappers\Python\test\test_cropped_readers.py", line 66, in check_values
>     np.testing.assert_array_equal(cropped_array, read_cropped_array)
>   File "C:\Users\lhe97136\Miniconda3\envs\vtk8-viewer\lib\site-packages\numpy\testing\_private\utils.py", line 935, in assert_array_equal
>     verbose=verbose, header='Arrays are not equal')
>   File "C:\Users\lhe97136\Miniconda3\envs\vtk8-viewer\lib\site-packages\numpy\testing\_private\utils.py", line 844, in assert_array_compare
>     raise AssertionError(msg)
> AssertionError:
> Arrays are not equal
> 
> Mismatched elements: 72 / 72 (100%)
> Max absolute difference: 250
> Max relative difference: 6.94444444
>  x: array([[[24, 25, 26, 27, 28, 29],
>         [30, 31, 32, 33, 34, 35],
>         [36, 37, 38, 39, 40, 41],...
>  y: array([[[42, 43, 44, 45, 46, 47],
>         [36, 37, 38, 39, 40, 41],
>         [30, 31, 32, 33, 34, 35],...
> 
> ======================================================================
> FAIL: test_tiff_resample_reader (test_resample_readers.TestResampleReaders)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\Users\lhe97136\Work\CCPi\CILViewer\Wrappers\Python\test\test_resample_readers.py", line 152, in test_tiff_resample_reader
>     self.resample_reader_test1(reader, 100 * 8 * 2)
>   File "C:\Users\lhe97136\Work\CCPi\CILViewer\Wrappers\Python\test\test_resample_readers.py", line 134, in resample_reader_test1
>     np.testing.assert_array_equal(np.asfortranarray(self.input_3D_array), resulting_array)
>   File "C:\Users\lhe97136\Miniconda3\envs\vtk8-viewer\lib\site-packages\numpy\testing\_private\utils.py", line 935, in assert_array_equal
>     verbose=verbose, header='Arrays are not equal')
>   File "C:\Users\lhe97136\Miniconda3\envs\vtk8-viewer\lib\site-packages\numpy\testing\_private\utils.py", line 844, in assert_array_compare
>     raise AssertionError(msg)
> AssertionError:
> Arrays are not equal
> 
> Mismatched elements: 300 / 300 (100%)
> Max absolute difference: 65530
> Max relative difference: 2184.33333333
>  x: array([[[  0,   1,   2,   3,   4,   5],
>         [  6,   7,   8,   9,  10,  11],
>         [ 12,  13,  14,  15,  16,  17],...
>  y: array([[[ 54,  55,  56,  57,  58,  59],
>         [ 48,  49,  50,  51,  52,  53],
>         [ 42,  43,  44,  45,  46,  47],...
> 
> ----------------------------------------------------------------------
> Ran 19 tests in 2.704s
> 
> FAILED (failures=2)

**Comment by lauramurgatroyd** [comment]
This was merged into vtk between version 8.1.2 and version 9
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/6155
The issue mentions files being read in reverse order so maybe this is what changed?

**Comment by lauramurgatroyd** [comment]
The same dataset read with vtk 8 and vtk 9:

VTK 8.1.2:
![image](https://user-images.githubusercontent.com/60604372/181721213-cad383a9-fc1a-48a3-b6f6-d99ff2602e24.png)


VTK 9.1:
![image](https://user-images.githubusercontent.com/60604372/181720935-80aede68-1613-4f50-ba0a-5ed5ee096dd7.png)





The code used in both cases:

import vtk
from ccpi.viewer.iviewer import SingleViewerCenterWidget

```python
from PySide2 import QtWidgets
import sys

reader = vtk.vtkTIFFReader()
reader.SetFileName(filename)
reader.Update() 

data = reader.GetOutput()
app = QtWidgets.QApplication(sys.argv)

window = SingleViewerCenterWidget()
window.set_input(data)
sys.exit(app.exec_())
```

**Comment by lauramurgatroyd** [comment]
Performing:
`np.flip(np_data, axis=1)`
on the first result, transforms it to the 2nd result.

This reverses the y axis

https://numpy.org/doc/stable/reference/generated/numpy.flip.html
