### ISSUE TITLE
Standalone viewer should support 4D HDF5 files

### ISSUE THREAD

**Issue by lauramurgatroyd** [vais-ral/CILViewer#345]
![image](https://github.com/vais-ral/CILViewer/assets/60604372/c99d7c0b-ad28-4f7a-bf7c-be5484c00c4b)

> 
> "Traceback (most recent call last):
>   File "C:\Users\gemst\miniconda3\envs\cil-viewer\lib\site-packages\eqt\threading\QtThreading.py", line 50, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "C:\Users\gemst\miniconda3\envs\cil-viewer\lib\site-packages\ccpi\viewer\utils\io.py", line 254, in Read
>     reader = self._GetReader(progress_callback)
>   File "C:\Users\gemst\miniconda3\envs\cil-viewer\lib\site-packages\ccpi\viewer\utils\io.py", line 345, in _GetReader
>     reader.SetFileName(self._FileName)
>   File "C:\Users\gemst\miniconda3\envs\cil-viewer\lib\site-packages\ccpi\viewer\utils\conversion.py", line 660, in SetFileName
>     self.ReadDataSetInfo()
>   File "C:\Users\gemst\miniconda3\envs\cil-viewer\lib\site-packages\ccpi\viewer\utils\conversion.py", line 678, in ReadDataSetInfo
>     self.SetStoredArrayShape(shape)
>   File "C:\Users\gemst\miniconda3\envs\cil-viewer\lib\site-packages\ccpi\viewer\utils\conversion.py", line 418, in SetStoredArrayShape
>     raise ValueError('Expected tuple of length 3, got {}'.format(len(value)))
> ValueError: Expected tuple of length 3, got 4
> "

**Comment by paskino** [comment]
This would require that the interface has a control over the 4th dimension, which currently hasn't.

A slider could do.
